# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[25,)" #mandatory (24 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/SpecialEffect/SpecialEffectMinecraftMods" #optional

[[mods]]
modId="eyegaze"
version="${file.jarVersion}"
displayName="eyegaze"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.eyegaze]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.eyegaze]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="continuouslydestroy"
version="${file.jarVersion}"
displayName="continuouslydestroy"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.continuouslydestroy]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.continuouslydestroy]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="gatherdrops"
version="${file.jarVersion}"
displayName="gatherdrops"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.gatherdrops]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.gatherdrops]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="autodestroy"
version="${file.jarVersion}"
displayName="autodestroy"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.autodestroy]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.autodestroy]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="autoopendoors"
version="${file.jarVersion}"
displayName="autoopendoors"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.autoopendoors]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.autoopendoors]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="autopillar"
version="${file.jarVersion}"
displayName="autopillar"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.autopillar]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.autopillar]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="continuouslyattack"
version="${file.jarVersion}"
displayName="continuouslyattack"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.continuouslyattack]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.continuouslyattack]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="openchat"
version="${file.jarVersion}"
displayName="openchat"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.openchat]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.openchat]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="opentableschests"
version="${file.jarVersion}"
displayName="opentableschests"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.opentableschests]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.opentableschests]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="pickblock"
version="${file.jarVersion}"
displayName="pickblock"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.pickblock]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.pickblock]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="quickcommands"
version="${file.jarVersion}"
displayName="quickcommands"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.quickcommands]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.quickcommands]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="swapmineplace"
version="${file.jarVersion}"
displayName="swapmineplace"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.swapmineplace]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.swapmineplace]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="useitem"
version="${file.jarVersion}"
displayName="useitem"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.useitem]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.useitem]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="mousehandler"
version="${file.jarVersion}"
displayName="mousehandler"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.mousehandler]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.mousehandler]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="autofly"
version="${file.jarVersion}"
displayName="autofly"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.autofly]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.autofly]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="autojump"
version="${file.jarVersion}"
displayName="autojump"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.autojump]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.autojump]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="dismount"
version="${file.jarVersion}"
displayName="dismount"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.dismount]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.dismount]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="easyladderclimb"
version="${file.jarVersion}"
displayName="easyladderclimb"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.easyladderclimb]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.easyladderclimb]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="movewithgaze"
version="${file.jarVersion}"
displayName="movewithgaze"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.movewithgaze]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.movewithgaze]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="sneaktoggle"
version="${file.jarVersion}"
displayName="sneaktoggle"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.sneaktoggle]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.sneaktoggle]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="debugfps"
version="${file.jarVersion}"
displayName="debugfps"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.debugfps]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.debugfps]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

[[mods]]
modId="modstategui"
version="${file.jarVersion}"
displayName="modstategui"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.modstategui]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.modstategui]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="BOTH"

