# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[25,)" #mandatory (24 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/SpecialEffect/SpecialEffectMinecraftMods" #optional
logoFile="eyemine_logo.png"

[[mods]]
modId="eyemine"
version="${file.jarVersion}"
displayName="EyeMine"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.eyemine]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="CLIENT"
[[dependencies.eyemine]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="CLIENT"

[[mods]]
modId="creativetabs"
version="${file.jarVersion}"
displayName="EyeInventory"
displayURL="https://www.specialeffect.org.uk/eyemine"
authors="Kirsty McNaught"
[[dependencies.creativetabs]]
	modId="forge"
	mandatory=true
	versionRange="[25,)"
	ordering="NONE"
	side="CLIENT"
[[dependencies.creativetabs]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.14.4]"
	ordering="NONE"
	side="CLIENT"
